name: dart_google_java_format
description: "A dart wrapper around 'google-java-format' tool for formatting Java files."
version: 0.1.0
homepage: https://github.com/invertase/dart-google-java-format

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  melos: ^1.4.0
  path: ^1.8.1
executables:
  dart_google_java_format: